spring:
  freemarker:
    cache: false
  devtools:
    livereload:
      enabled: true
  thymeleaf:
        cache: false
        enabled: false

  datasource:
      driverClassName : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: "jdbc:log4jdbc:mariadb://moimdev.cxz28d3n4hpj.ap-northeast-2.rds.amazonaws.com:3306/review"
      username: csj2702
      password: tjdwns2702
  jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
  jackson:
    time-zone: UTC
    serialization:
                  WRITE_DATES_AS_TIMESTAMPS : false
                  FAIL_ON_EMPTY_BEANS : false
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB  session:    timeout: 86400100
                        
logging:
        level:
              com:
                  devson: 
                          pagination: debug
                          
server:
    port: 8080

webImagePath: /Users/choiseongjun/git/Review/image/
app:
      jwtSecret : JWTSuperSecretKey
      jwtExpirationInMs : 864000
      